/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CleanCachePolicy
 */
public class CleanCachePolicyTest {
    private final CleanCachePolicy model = new CleanCachePolicy();

    /**
     * Model tests for CleanCachePolicy
     */
    @Test
    public void testCleanCachePolicy() {
        // TODO: test CleanCachePolicy
    }

    /**
     * Test the property 'gracePeriodSeconds'
     */
    @Test
    public void gracePeriodSecondsTest() {
        // TODO: test gracePeriodSeconds
    }

    /**
     * Test the property 'maxRetryAttempts'
     */
    @Test
    public void maxRetryAttemptsTest() {
        // TODO: test maxRetryAttempts
    }

}
