/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import models.DatasetCondition;
import models.HCFSStatus;
import models.Mount;
import models.Runtime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DatasetStatus
 */
public class DatasetStatusTest {
    private final DatasetStatus model = new DatasetStatus();

    /**
     * Model tests for DatasetStatus
     */
    @Test
    public void testDatasetStatus() {
        // TODO: test DatasetStatus
    }

    /**
     * Test the property 'cacheStates'
     */
    @Test
    public void cacheStatesTest() {
        // TODO: test cacheStates
    }

    /**
     * Test the property 'conditions'
     */
    @Test
    public void conditionsTest() {
        // TODO: test conditions
    }

    /**
     * Test the property 'dataBackupRef'
     */
    @Test
    public void dataBackupRefTest() {
        // TODO: test dataBackupRef
    }

    /**
     * Test the property 'dataLoadRef'
     */
    @Test
    public void dataLoadRefTest() {
        // TODO: test dataLoadRef
    }

    /**
     * Test the property 'datasetRef'
     */
    @Test
    public void datasetRefTest() {
        // TODO: test datasetRef
    }

    /**
     * Test the property 'fileNum'
     */
    @Test
    public void fileNumTest() {
        // TODO: test fileNum
    }

    /**
     * Test the property 'hcfs'
     */
    @Test
    public void hcfsTest() {
        // TODO: test hcfs
    }

    /**
     * Test the property 'mounts'
     */
    @Test
    public void mountsTest() {
        // TODO: test mounts
    }

    /**
     * Test the property 'operationRef'
     */
    @Test
    public void operationRefTest() {
        // TODO: test operationRef
    }

    /**
     * Test the property 'phase'
     */
    @Test
    public void phaseTest() {
        // TODO: test phase
    }

    /**
     * Test the property 'runtimes'
     */
    @Test
    public void runtimesTest() {
        // TODO: test runtimes
    }

    /**
     * Test the property 'ufsTotal'
     */
    @Test
    public void ufsTotalTest() {
        // TODO: test ufsTotal
    }

}
