/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.OperationRef;
import models.User;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DataBackupSpec
 */
public class DataBackupSpecTest {
    private final DataBackupSpec model = new DataBackupSpec();

    /**
     * Model tests for DataBackupSpec
     */
    @Test
    public void testDataBackupSpec() {
        // TODO: test DataBackupSpec
    }

    /**
     * Test the property 'backupPath'
     */
    @Test
    public void backupPathTest() {
        // TODO: test backupPath
    }

    /**
     * Test the property 'dataset'
     */
    @Test
    public void datasetTest() {
        // TODO: test dataset
    }

    /**
     * Test the property 'runAfter'
     */
    @Test
    public void runAfterTest() {
        // TODO: test runAfter
    }

    /**
     * Test the property 'runAs'
     */
    @Test
    public void runAsTest() {
        // TODO: test runAs
    }

    /**
     * Test the property 'ttlSecondsAfterFinished'
     */
    @Test
    public void ttlSecondsAfterFinishedTest() {
        // TODO: test ttlSecondsAfterFinished
    }

}
