/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DataRestoreLocation
 */
public class DataRestoreLocationTest {
    private final DataRestoreLocation model = new DataRestoreLocation();

    /**
     * Model tests for DataRestoreLocation
     */
    @Test
    public void testDataRestoreLocation() {
        // TODO: test DataRestoreLocation
    }

    /**
     * Test the property 'nodeName'
     */
    @Test
    public void nodeNameTest() {
        // TODO: test nodeName
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

}
