/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.CleanCachePolicy;
import models.EFCCompTemplateSpec;
import models.EFCFuseSpec;
import models.InitFuseSpec;
import models.OSAdvise;
import models.PodMetadata;
import models.TieredStore;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EFCRuntimeSpec
 */
public class EFCRuntimeSpecTest {
    private final EFCRuntimeSpec model = new EFCRuntimeSpec();

    /**
     * Model tests for EFCRuntimeSpec
     */
    @Test
    public void testEFCRuntimeSpec() {
        // TODO: test EFCRuntimeSpec
    }

    /**
     * Test the property 'cleanCachePolicy'
     */
    @Test
    public void cleanCachePolicyTest() {
        // TODO: test cleanCachePolicy
    }

    /**
     * Test the property 'fuse'
     */
    @Test
    public void fuseTest() {
        // TODO: test fuse
    }

    /**
     * Test the property 'initFuse'
     */
    @Test
    public void initFuseTest() {
        // TODO: test initFuse
    }

    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }

    /**
     * Test the property 'osAdvise'
     */
    @Test
    public void osAdviseTest() {
        // TODO: test osAdvise
    }

    /**
     * Test the property 'podMetadata'
     */
    @Test
    public void podMetadataTest() {
        // TODO: test podMetadata
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    public void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'tieredstore'
     */
    @Test
    public void tieredstoreTest() {
        // TODO: test tieredstore
    }

    /**
     * Test the property 'worker'
     */
    @Test
    public void workerTest() {
        // TODO: test worker
    }

}
