/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import models.EncryptOption;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExternalEndpointSpec
 */
public class ExternalEndpointSpecTest {
    private final ExternalEndpointSpec model = new ExternalEndpointSpec();

    /**
     * Model tests for ExternalEndpointSpec
     */
    @Test
    public void testExternalEndpointSpec() {
        // TODO: test ExternalEndpointSpec
    }

    /**
     * Test the property 'encryptOptions'
     */
    @Test
    public void encryptOptionsTest() {
        // TODO: test encryptOptions
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

}
