/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import models.CleanCachePolicy;
import models.Data;
import models.GooseFSCompTemplateSpec;
import models.GooseFSFuseSpec;
import models.InitUsersSpec;
import models.TieredStore;
import models.User;
import models.VersionSpec;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GooseFSRuntimeSpec
 */
public class GooseFSRuntimeSpecTest {
    private final GooseFSRuntimeSpec model = new GooseFSRuntimeSpec();

    /**
     * Model tests for GooseFSRuntimeSpec
     */
    @Test
    public void testGooseFSRuntimeSpec() {
        // TODO: test GooseFSRuntimeSpec
    }

    /**
     * Test the property 'apiGateway'
     */
    @Test
    public void apiGatewayTest() {
        // TODO: test apiGateway
    }

    /**
     * Test the property 'cleanCachePolicy'
     */
    @Test
    public void cleanCachePolicyTest() {
        // TODO: test cleanCachePolicy
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'disablePrometheus'
     */
    @Test
    public void disablePrometheusTest() {
        // TODO: test disablePrometheus
    }

    /**
     * Test the property 'fuse'
     */
    @Test
    public void fuseTest() {
        // TODO: test fuse
    }

    /**
     * Test the property 'goosefsVersion'
     */
    @Test
    public void goosefsVersionTest() {
        // TODO: test goosefsVersion
    }

    /**
     * Test the property 'hadoopConfig'
     */
    @Test
    public void hadoopConfigTest() {
        // TODO: test hadoopConfig
    }

    /**
     * Test the property 'initUsers'
     */
    @Test
    public void initUsersTest() {
        // TODO: test initUsers
    }

    /**
     * Test the property 'jobMaster'
     */
    @Test
    public void jobMasterTest() {
        // TODO: test jobMaster
    }

    /**
     * Test the property 'jobWorker'
     */
    @Test
    public void jobWorkerTest() {
        // TODO: test jobWorker
    }

    /**
     * Test the property 'jvmOptions'
     */
    @Test
    public void jvmOptionsTest() {
        // TODO: test jvmOptions
    }

    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    public void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'runAs'
     */
    @Test
    public void runAsTest() {
        // TODO: test runAs
    }

    /**
     * Test the property 'tieredstore'
     */
    @Test
    public void tieredstoreTest() {
        // TODO: test tieredstore
    }

    /**
     * Test the property 'worker'
     */
    @Test
    public void workerTest() {
        // TODO: test worker
    }

}
