/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import models.CleanCachePolicy;
import models.InitUsersSpec;
import models.JuiceFSCompTemplateSpec;
import models.JuiceFSFuseSpec;
import models.PodMetadata;
import models.TieredStore;
import models.User;
import models.V1Volume;
import models.VersionSpec;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JuiceFSRuntimeSpec
 */
public class JuiceFSRuntimeSpecTest {
    private final JuiceFSRuntimeSpec model = new JuiceFSRuntimeSpec();

    /**
     * Model tests for JuiceFSRuntimeSpec
     */
    @Test
    public void testJuiceFSRuntimeSpec() {
        // TODO: test JuiceFSRuntimeSpec
    }

    /**
     * Test the property 'cleanCachePolicy'
     */
    @Test
    public void cleanCachePolicyTest() {
        // TODO: test cleanCachePolicy
    }

    /**
     * Test the property 'configs'
     */
    @Test
    public void configsTest() {
        // TODO: test configs
    }

    /**
     * Test the property 'disablePrometheus'
     */
    @Test
    public void disablePrometheusTest() {
        // TODO: test disablePrometheus
    }

    /**
     * Test the property 'fuse'
     */
    @Test
    public void fuseTest() {
        // TODO: test fuse
    }

    /**
     * Test the property 'initUsers'
     */
    @Test
    public void initUsersTest() {
        // TODO: test initUsers
    }

    /**
     * Test the property 'jobWorker'
     */
    @Test
    public void jobWorkerTest() {
        // TODO: test jobWorker
    }

    /**
     * Test the property 'juicefsVersion'
     */
    @Test
    public void juicefsVersionTest() {
        // TODO: test juicefsVersion
    }

    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }

    /**
     * Test the property 'podMetadata'
     */
    @Test
    public void podMetadataTest() {
        // TODO: test podMetadata
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    public void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'runAs'
     */
    @Test
    public void runAsTest() {
        // TODO: test runAs
    }

    /**
     * Test the property 'tieredstore'
     */
    @Test
    public void tieredstoreTest() {
        // TODO: test tieredstore
    }

    /**
     * Test the property 'volumes'
     */
    @Test
    public void volumesTest() {
        // TODO: test volumes
    }

    /**
     * Test the property 'worker'
     */
    @Test
    public void workerTest() {
        // TODO: test worker
    }

}
