/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.V1Time;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RuntimeCondition
 */
public class RuntimeConditionTest {
    private final RuntimeCondition model = new RuntimeCondition();

    /**
     * Model tests for RuntimeCondition
     */
    @Test
    public void testRuntimeCondition() {
        // TODO: test RuntimeCondition
    }

    /**
     * Test the property 'lastProbeTime'
     */
    @Test
    public void lastProbeTimeTest() {
        // TODO: test lastProbeTime
    }

    /**
     * Test the property 'lastTransitionTime'
     */
    @Test
    public void lastTransitionTimeTest() {
        // TODO: test lastTransitionTime
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
