/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.CleanCachePolicy;
import models.MetadataSyncPolicy;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RuntimeManagement
 */
public class RuntimeManagementTest {
    private final RuntimeManagement model = new RuntimeManagement();

    /**
     * Model tests for RuntimeManagement
     */
    @Test
    public void testRuntimeManagement() {
        // TODO: test RuntimeManagement
    }

    /**
     * Test the property 'cleanCachePolicy'
     */
    @Test
    public void cleanCachePolicyTest() {
        // TODO: test cleanCachePolicy
    }

    /**
     * Test the property 'metadataSyncPolicy'
     */
    @Test
    public void metadataSyncPolicyTest() {
        // TODO: test metadataSyncPolicy
    }

}
