/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TargetDatasetWithMountPath
 */
public class TargetDatasetWithMountPathTest {
    private final TargetDatasetWithMountPath model = new TargetDatasetWithMountPath();

    /**
     * Model tests for TargetDatasetWithMountPath
     */
    @Test
    public void testTargetDatasetWithMountPath() {
        // TODO: test TargetDatasetWithMountPath
    }

    /**
     * Test the property 'mountPath'
     */
    @Test
    public void mountPathTest() {
        // TODO: test mountPath
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'subPath'
     */
    @Test
    public void subPathTest() {
        // TODO: test subPath
    }

}
