/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import models.ThinCompTemplateSpec;
import models.ThinFuseSpec;
import models.V1Volume;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ThinRuntimeProfileSpec
 */
public class ThinRuntimeProfileSpecTest {
    private final ThinRuntimeProfileSpec model = new ThinRuntimeProfileSpec();

    /**
     * Model tests for ThinRuntimeProfileSpec
     */
    @Test
    public void testThinRuntimeProfileSpec() {
        // TODO: test ThinRuntimeProfileSpec
    }

    /**
     * Test the property 'fileSystemType'
     */
    @Test
    public void fileSystemTypeTest() {
        // TODO: test fileSystemType
    }

    /**
     * Test the property 'fuse'
     */
    @Test
    public void fuseTest() {
        // TODO: test fuse
    }

    /**
     * Test the property 'nodePublishSecretPolicy'
     */
    @Test
    public void nodePublishSecretPolicyTest() {
        // TODO: test nodePublishSecretPolicy
    }

    /**
     * Test the property 'volumes'
     */
    @Test
    public void volumesTest() {
        // TODO: test volumes
    }

    /**
     * Test the property 'worker'
     */
    @Test
    public void workerTest() {
        // TODO: test worker
    }

}
