/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import models.Level;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TieredStore
 */
public class TieredStoreTest {
    private final TieredStore model = new TieredStore();

    /**
     * Model tests for TieredStore
     */
    @Test
    public void testTieredStore() {
        // TODO: test TieredStore
    }

    /**
     * Test the property 'levels'
     */
    @Test
    public void levelsTest() {
        // TODO: test levels
    }

}
