/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import models.MasterSpec;
import models.TieredStore;
import models.V1Volume;
import models.VineyardCompTemplateSpec;
import models.VineyardSockSpec;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VineyardRuntimeSpec
 */
public class VineyardRuntimeSpecTest {
    private final VineyardRuntimeSpec model = new VineyardRuntimeSpec();

    /**
     * Model tests for VineyardRuntimeSpec
     */
    @Test
    public void testVineyardRuntimeSpec() {
        // TODO: test VineyardRuntimeSpec
    }

    /**
     * Test the property 'disablePrometheus'
     */
    @Test
    public void disablePrometheusTest() {
        // TODO: test disablePrometheus
    }

    /**
     * Test the property 'fuse'
     */
    @Test
    public void fuseTest() {
        // TODO: test fuse
    }

    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }

    /**
     * Test the property 'tieredstore'
     */
    @Test
    public void tieredstoreTest() {
        // TODO: test tieredstore
    }

    /**
     * Test the property 'volumes'
     */
    @Test
    public void volumesTest() {
        // TODO: test volumes
    }

    /**
     * Test the property 'worker'
     */
    @Test
    public void workerTest() {
        // TODO: test worker
    }

}
