/*
 * fluid
 * Python SDK for fluid
 *
 * OpenAPI spec version: v0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluid_cloudnative.fluid;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.proto.Meta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Condition explains the transitions on phase
 */
@ApiModel(description = "Condition explains the transitions on phase")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-14T16:48:53.494+08:00")
public class Condition {
  @SerializedName("lastProbeTime")
  private Meta.Time lastProbeTime = null;

  @SerializedName("lastTransitionTime")
  private Meta.Time lastTransitionTime = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("type")
  private String type = null;

  public Condition lastProbeTime(Meta.Time lastProbeTime) {
    this.lastProbeTime = lastProbeTime;
    return this;
  }

   /**
   * LastProbeTime describes last time this condition was updated.
   * @return lastProbeTime
  **/
  @ApiModelProperty(value = "LastProbeTime describes last time this condition was updated.")
  public Meta.Time getLastProbeTime() {
    return lastProbeTime;
  }

  public void setLastProbeTime(Meta.Time lastProbeTime) {
    this.lastProbeTime = lastProbeTime;
  }

  public Condition lastTransitionTime(Meta.Time lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
    return this;
  }

   /**
   * LastTransitionTime describes last time the condition transitioned from one status to another.
   * @return lastTransitionTime
  **/
  @ApiModelProperty(value = "LastTransitionTime describes last time the condition transitioned from one status to another.")
  public Meta.Time getLastTransitionTime() {
    return lastTransitionTime;
  }

  public void setLastTransitionTime(Meta.Time lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
  }

  public Condition message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message is a human-readable message indicating details about the transition
   * @return message
  **/
  @ApiModelProperty(value = "Message is a human-readable message indicating details about the transition")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public Condition reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason for the condition&#39;s last transition
   * @return reason
  **/
  @ApiModelProperty(value = "Reason for the condition's last transition")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public Condition status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the condition, one of &#x60;True&#x60;, &#x60;False&#x60; or &#x60;Unknown&#x60;
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of the condition, one of `True`, `False` or `Unknown`")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Condition type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of condition, either &#x60;Complete&#x60; or &#x60;Failed&#x60;
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of condition, either `Complete` or `Failed`")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Condition condition = (Condition) o;
    return Objects.equals(this.lastProbeTime, condition.lastProbeTime) &&
        Objects.equals(this.lastTransitionTime, condition.lastTransitionTime) &&
        Objects.equals(this.message, condition.message) &&
        Objects.equals(this.reason, condition.reason) &&
        Objects.equals(this.status, condition.status) &&
        Objects.equals(this.type, condition.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastProbeTime, lastTransitionTime, message, reason, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Condition {\n");
    
    sb.append("    lastProbeTime: ").append(toIndentedString(lastProbeTime)).append("\n");
    sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

