/*
 * fluid
 * Python SDK for fluid
 *
 * OpenAPI spec version: v0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluid_cloudnative.fluid;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * Data management strategies
 */
@ApiModel(description = "Data management strategies")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-14T16:48:53.494+08:00")
public class Data {
  @SerializedName("pin")
  private Boolean pin = null;

  @SerializedName("replicas")
  private Integer replicas = null;

  public Data pin(Boolean pin) {
    this.pin = pin;
    return this;
  }

   /**
   * Pin the dataset or not. Refer to &lt;a href&#x3D;\&quot;https://docs.alluxio.io/os/user/stable/en/operation/User-CLI.html#pin\&quot;&gt;Alluxio User-CLI pin&lt;/a&gt;
   * @return pin
  **/
  @ApiModelProperty(value = "Pin the dataset or not. Refer to <a href=\"https://docs.alluxio.io/os/user/stable/en/operation/User-CLI.html#pin\">Alluxio User-CLI pin</a>")
  public Boolean isPin() {
    return pin;
  }

  public void setPin(Boolean pin) {
    this.pin = pin;
  }

  public Data replicas(Integer replicas) {
    this.replicas = replicas;
    return this;
  }

   /**
   * The copies of the dataset
   * @return replicas
  **/
  @ApiModelProperty(value = "The copies of the dataset")
  public Integer getReplicas() {
    return replicas;
  }

  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data data = (Data) o;
    return Objects.equals(this.pin, data.pin) &&
        Objects.equals(this.replicas, data.replicas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pin, replicas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data {\n");
    
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

