/*
 * fluid
 * Python SDK for fluid
 *
 * OpenAPI spec version: v0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluid_cloudnative.fluid;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DataLoadStatus defines the observed state of DataLoad
 */
@ApiModel(description = "DataLoadStatus defines the observed state of DataLoad")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-14T16:48:53.494+08:00")
public class DataLoadStatus {
  @SerializedName("conditions")
  private List<Condition> conditions = new ArrayList<Condition>();

  @SerializedName("duration")
  private String duration = null;

  @SerializedName("phase")
  private String phase = null;

  public DataLoadStatus conditions(List<Condition> conditions) {
    this.conditions = conditions;
    return this;
  }

  public DataLoadStatus addConditionsItem(Condition conditionsItem) {
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions consists of transition information on DataLoad&#39;s Phase
   * @return conditions
  **/
  @ApiModelProperty(required = true, value = "Conditions consists of transition information on DataLoad's Phase")
  public List<Condition> getConditions() {
    return conditions;
  }

  public void setConditions(List<Condition> conditions) {
    this.conditions = conditions;
  }

  public DataLoadStatus duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration tell user how much time was spent to load the data
   * @return duration
  **/
  @ApiModelProperty(required = true, value = "Duration tell user how much time was spent to load the data")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public DataLoadStatus phase(String phase) {
    this.phase = phase;
    return this;
  }

   /**
   * Phase describes current phase of DataLoad
   * @return phase
  **/
  @ApiModelProperty(required = true, value = "Phase describes current phase of DataLoad")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataLoadStatus dataLoadStatus = (DataLoadStatus) o;
    return Objects.equals(this.conditions, dataLoadStatus.conditions) &&
        Objects.equals(this.duration, dataLoadStatus.duration) &&
        Objects.equals(this.phase, dataLoadStatus.phase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, duration, phase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataLoadStatus {\n");
    
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

