/*
 * fluid
 * Python SDK for fluid
 *
 * OpenAPI spec version: v0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluid_cloudnative.fluid;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * EncryptOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-14T16:48:53.494+08:00")
public class EncryptOption {
  @SerializedName("name")
  private String name = null;

  @SerializedName("valueFrom")
  private EncryptOptionSource valueFrom = null;

  public EncryptOption name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of encryptOption
   * @return name
  **/
  @ApiModelProperty(value = "The name of encryptOption")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EncryptOption valueFrom(EncryptOptionSource valueFrom) {
    this.valueFrom = valueFrom;
    return this;
  }

   /**
   * The valueFrom of encryptOption
   * @return valueFrom
  **/
  @ApiModelProperty(value = "The valueFrom of encryptOption")
  public EncryptOptionSource getValueFrom() {
    return valueFrom;
  }

  public void setValueFrom(EncryptOptionSource valueFrom) {
    this.valueFrom = valueFrom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EncryptOption encryptOption = (EncryptOption) o;
    return Objects.equals(this.name, encryptOption.name) &&
        Objects.equals(this.valueFrom, encryptOption.valueFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, valueFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EncryptOption {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    valueFrom: ").append(toIndentedString(valueFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

