/*
 * fluid
 * Python SDK for fluid
 *
 * OpenAPI spec version: v0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluid_cloudnative.fluid;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * User explains the user and group to run a Container
 */
@ApiModel(description = "User explains the user and group to run a Container")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-14T16:48:53.494+08:00")
public class User {
  @SerializedName("gid")
  private Long gid = null;

  @SerializedName("group")
  private String group = null;

  @SerializedName("uid")
  private Long uid = null;

  @SerializedName("user")
  private String user = null;

  public User gid(Long gid) {
    this.gid = gid;
    return this;
  }

   /**
   * The gid to run the alluxio runtime
   * @return gid
  **/
  @ApiModelProperty(required = true, value = "The gid to run the alluxio runtime")
  public Long getGid() {
    return gid;
  }

  public void setGid(Long gid) {
    this.gid = gid;
  }

  public User group(String group) {
    this.group = group;
    return this;
  }

   /**
   * The group name to run the alluxio runtime
   * @return group
  **/
  @ApiModelProperty(required = true, value = "The group name to run the alluxio runtime")
  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public User uid(Long uid) {
    this.uid = uid;
    return this;
  }

   /**
   * The uid to run the alluxio runtime
   * @return uid
  **/
  @ApiModelProperty(required = true, value = "The uid to run the alluxio runtime")
  public Long getUid() {
    return uid;
  }

  public void setUid(Long uid) {
    this.uid = uid;
  }

  public User user(String user) {
    this.user = user;
    return this;
  }

   /**
   * The user name to run the alluxio runtime
   * @return user
  **/
  @ApiModelProperty(required = true, value = "The user name to run the alluxio runtime")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.gid, user.gid) &&
        Objects.equals(this.group, user.group) &&
        Objects.equals(this.uid, user.uid) &&
        Objects.equals(this.user, user.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gid, group, uid, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    gid: ").append(toIndentedString(gid)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

