/*
 * fluid
 * Python SDK for fluid
 *
 * OpenAPI spec version: v0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluid_cloudnative.fluid;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VersionSpec represents the settings for the  version that fluid is orchestrating.
 */
@ApiModel(description = "VersionSpec represents the settings for the  version that fluid is orchestrating.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-14T16:48:53.494+08:00")
public class VersionSpec {
  @SerializedName("image")
  private String image = null;

  @SerializedName("imagePullPolicy")
  private String imagePullPolicy = null;

  @SerializedName("imageTag")
  private String imageTag = null;

  public VersionSpec image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Image (e.g. alluxio/alluxio)
   * @return image
  **/
  @ApiModelProperty(value = "Image (e.g. alluxio/alluxio)")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public VersionSpec imagePullPolicy(String imagePullPolicy) {
    this.imagePullPolicy = imagePullPolicy;
    return this;
  }

   /**
   * One of the three policies: &#x60;Always&#x60;, &#x60;IfNotPresent&#x60;, &#x60;Never&#x60;
   * @return imagePullPolicy
  **/
  @ApiModelProperty(value = "One of the three policies: `Always`, `IfNotPresent`, `Never`")
  public String getImagePullPolicy() {
    return imagePullPolicy;
  }

  public void setImagePullPolicy(String imagePullPolicy) {
    this.imagePullPolicy = imagePullPolicy;
  }

  public VersionSpec imageTag(String imageTag) {
    this.imageTag = imageTag;
    return this;
  }

   /**
   * Image tag (e.g. 2.3.0-SNAPSHOT)
   * @return imageTag
  **/
  @ApiModelProperty(value = "Image tag (e.g. 2.3.0-SNAPSHOT)")
  public String getImageTag() {
    return imageTag;
  }

  public void setImageTag(String imageTag) {
    this.imageTag = imageTag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionSpec versionSpec = (VersionSpec) o;
    return Objects.equals(this.image, versionSpec.image) &&
        Objects.equals(this.imagePullPolicy, versionSpec.imagePullPolicy) &&
        Objects.equals(this.imageTag, versionSpec.imageTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(image, imagePullPolicy, imageTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionSpec {\n");
    
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imagePullPolicy: ").append(toIndentedString(imagePullPolicy)).append("\n");
    sb.append("    imageTag: ").append(toIndentedString(imageTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

