/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import models.AlluxioCompTemplateSpec;
import models.AlluxioFuseSpec;
import models.Data;
import models.InitUsersSpec;
import models.PodMetadata;
import models.RuntimeManagement;
import models.TieredStore;
import models.User;
import models.V1Volume;
import models.VersionSpec;

/**
 * AlluxioRuntimeSpec defines the desired state of AlluxioRuntime
 */
@ApiModel(description = "AlluxioRuntimeSpec defines the desired state of AlluxioRuntime")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-30T14:39:14.140796+08:00[Asia/Shanghai]")
public class AlluxioRuntimeSpec {
  public static final String SERIALIZED_NAME_ALLUXIO_VERSION = "alluxioVersion";
  @SerializedName(SERIALIZED_NAME_ALLUXIO_VERSION)
  private VersionSpec alluxioVersion;

  public static final String SERIALIZED_NAME_API_GATEWAY = "apiGateway";
  @SerializedName(SERIALIZED_NAME_API_GATEWAY)
  private AlluxioCompTemplateSpec apiGateway;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private Data data;

  public static final String SERIALIZED_NAME_DISABLE_PROMETHEUS = "disablePrometheus";
  @SerializedName(SERIALIZED_NAME_DISABLE_PROMETHEUS)
  private Boolean disablePrometheus;

  public static final String SERIALIZED_NAME_FUSE = "fuse";
  @SerializedName(SERIALIZED_NAME_FUSE)
  private AlluxioFuseSpec fuse;

  public static final String SERIALIZED_NAME_HADOOP_CONFIG = "hadoopConfig";
  @SerializedName(SERIALIZED_NAME_HADOOP_CONFIG)
  private String hadoopConfig;

  public static final String SERIALIZED_NAME_INIT_USERS = "initUsers";
  @SerializedName(SERIALIZED_NAME_INIT_USERS)
  private InitUsersSpec initUsers;

  public static final String SERIALIZED_NAME_JOB_MASTER = "jobMaster";
  @SerializedName(SERIALIZED_NAME_JOB_MASTER)
  private AlluxioCompTemplateSpec jobMaster;

  public static final String SERIALIZED_NAME_JOB_WORKER = "jobWorker";
  @SerializedName(SERIALIZED_NAME_JOB_WORKER)
  private AlluxioCompTemplateSpec jobWorker;

  public static final String SERIALIZED_NAME_JVM_OPTIONS = "jvmOptions";
  @SerializedName(SERIALIZED_NAME_JVM_OPTIONS)
  private List<String> jvmOptions = null;

  public static final String SERIALIZED_NAME_MANAGEMENT = "management";
  @SerializedName(SERIALIZED_NAME_MANAGEMENT)
  private RuntimeManagement management;

  public static final String SERIALIZED_NAME_MASTER = "master";
  @SerializedName(SERIALIZED_NAME_MASTER)
  private AlluxioCompTemplateSpec master;

  public static final String SERIALIZED_NAME_POD_METADATA = "podMetadata";
  @SerializedName(SERIALIZED_NAME_POD_METADATA)
  private PodMetadata podMetadata;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Map<String, String> properties = null;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_RUN_AS = "runAs";
  @SerializedName(SERIALIZED_NAME_RUN_AS)
  private User runAs;

  public static final String SERIALIZED_NAME_TIEREDSTORE = "tieredstore";
  @SerializedName(SERIALIZED_NAME_TIEREDSTORE)
  private TieredStore tieredstore;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  private List<V1Volume> volumes = null;

  public static final String SERIALIZED_NAME_WORKER = "worker";
  @SerializedName(SERIALIZED_NAME_WORKER)
  private AlluxioCompTemplateSpec worker;


  public AlluxioRuntimeSpec alluxioVersion(VersionSpec alluxioVersion) {
    
    this.alluxioVersion = alluxioVersion;
    return this;
  }

   /**
   * Get alluxioVersion
   * @return alluxioVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VersionSpec getAlluxioVersion() {
    return alluxioVersion;
  }


  public void setAlluxioVersion(VersionSpec alluxioVersion) {
    this.alluxioVersion = alluxioVersion;
  }


  public AlluxioRuntimeSpec apiGateway(AlluxioCompTemplateSpec apiGateway) {
    
    this.apiGateway = apiGateway;
    return this;
  }

   /**
   * Get apiGateway
   * @return apiGateway
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlluxioCompTemplateSpec getApiGateway() {
    return apiGateway;
  }


  public void setApiGateway(AlluxioCompTemplateSpec apiGateway) {
    this.apiGateway = apiGateway;
  }


  public AlluxioRuntimeSpec data(Data data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Data getData() {
    return data;
  }


  public void setData(Data data) {
    this.data = data;
  }


  public AlluxioRuntimeSpec disablePrometheus(Boolean disablePrometheus) {
    
    this.disablePrometheus = disablePrometheus;
    return this;
  }

   /**
   * Disable monitoring for Alluxio Runtime Prometheus is enabled by default
   * @return disablePrometheus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable monitoring for Alluxio Runtime Prometheus is enabled by default")

  public Boolean getDisablePrometheus() {
    return disablePrometheus;
  }


  public void setDisablePrometheus(Boolean disablePrometheus) {
    this.disablePrometheus = disablePrometheus;
  }


  public AlluxioRuntimeSpec fuse(AlluxioFuseSpec fuse) {
    
    this.fuse = fuse;
    return this;
  }

   /**
   * Get fuse
   * @return fuse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlluxioFuseSpec getFuse() {
    return fuse;
  }


  public void setFuse(AlluxioFuseSpec fuse) {
    this.fuse = fuse;
  }


  public AlluxioRuntimeSpec hadoopConfig(String hadoopConfig) {
    
    this.hadoopConfig = hadoopConfig;
    return this;
  }

   /**
   * Name of the configMap used to support HDFS configurations when using HDFS as Alluxio&#39;s UFS. The configMap must be in the same namespace with the AlluxioRuntime. The configMap should contain user-specific HDFS conf files in it. For now, only \&quot;hdfs-site.xml\&quot; and \&quot;core-site.xml\&quot; are supported. It must take the filename of the conf file as the key and content of the file as the value.
   * @return hadoopConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the configMap used to support HDFS configurations when using HDFS as Alluxio's UFS. The configMap must be in the same namespace with the AlluxioRuntime. The configMap should contain user-specific HDFS conf files in it. For now, only \"hdfs-site.xml\" and \"core-site.xml\" are supported. It must take the filename of the conf file as the key and content of the file as the value.")

  public String getHadoopConfig() {
    return hadoopConfig;
  }


  public void setHadoopConfig(String hadoopConfig) {
    this.hadoopConfig = hadoopConfig;
  }


  public AlluxioRuntimeSpec initUsers(InitUsersSpec initUsers) {
    
    this.initUsers = initUsers;
    return this;
  }

   /**
   * Get initUsers
   * @return initUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InitUsersSpec getInitUsers() {
    return initUsers;
  }


  public void setInitUsers(InitUsersSpec initUsers) {
    this.initUsers = initUsers;
  }


  public AlluxioRuntimeSpec jobMaster(AlluxioCompTemplateSpec jobMaster) {
    
    this.jobMaster = jobMaster;
    return this;
  }

   /**
   * Get jobMaster
   * @return jobMaster
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlluxioCompTemplateSpec getJobMaster() {
    return jobMaster;
  }


  public void setJobMaster(AlluxioCompTemplateSpec jobMaster) {
    this.jobMaster = jobMaster;
  }


  public AlluxioRuntimeSpec jobWorker(AlluxioCompTemplateSpec jobWorker) {
    
    this.jobWorker = jobWorker;
    return this;
  }

   /**
   * Get jobWorker
   * @return jobWorker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlluxioCompTemplateSpec getJobWorker() {
    return jobWorker;
  }


  public void setJobWorker(AlluxioCompTemplateSpec jobWorker) {
    this.jobWorker = jobWorker;
  }


  public AlluxioRuntimeSpec jvmOptions(List<String> jvmOptions) {
    
    this.jvmOptions = jvmOptions;
    return this;
  }

  public AlluxioRuntimeSpec addJvmOptionsItem(String jvmOptionsItem) {
    if (this.jvmOptions == null) {
      this.jvmOptions = new ArrayList<String>();
    }
    this.jvmOptions.add(jvmOptionsItem);
    return this;
  }

   /**
   * Options for JVM
   * @return jvmOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Options for JVM")

  public List<String> getJvmOptions() {
    return jvmOptions;
  }


  public void setJvmOptions(List<String> jvmOptions) {
    this.jvmOptions = jvmOptions;
  }


  public AlluxioRuntimeSpec management(RuntimeManagement management) {
    
    this.management = management;
    return this;
  }

   /**
   * Get management
   * @return management
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RuntimeManagement getManagement() {
    return management;
  }


  public void setManagement(RuntimeManagement management) {
    this.management = management;
  }


  public AlluxioRuntimeSpec master(AlluxioCompTemplateSpec master) {
    
    this.master = master;
    return this;
  }

   /**
   * Get master
   * @return master
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlluxioCompTemplateSpec getMaster() {
    return master;
  }


  public void setMaster(AlluxioCompTemplateSpec master) {
    this.master = master;
  }


  public AlluxioRuntimeSpec podMetadata(PodMetadata podMetadata) {
    
    this.podMetadata = podMetadata;
    return this;
  }

   /**
   * Get podMetadata
   * @return podMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PodMetadata getPodMetadata() {
    return podMetadata;
  }


  public void setPodMetadata(PodMetadata podMetadata) {
    this.podMetadata = podMetadata;
  }


  public AlluxioRuntimeSpec properties(Map<String, String> properties) {
    
    this.properties = properties;
    return this;
  }

  public AlluxioRuntimeSpec putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<String, String>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Configurable properties for Alluxio system. &lt;br&gt; Refer to &lt;a href&#x3D;\&quot;https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html\&quot;&gt;Alluxio Configuration Properties&lt;/a&gt; for more info
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Configurable properties for Alluxio system. <br> Refer to <a href=\"https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html\">Alluxio Configuration Properties</a> for more info")

  public Map<String, String> getProperties() {
    return properties;
  }


  public void setProperties(Map<String, String> properties) {
    this.properties = properties;
  }


  public AlluxioRuntimeSpec replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * The replicas of the worker, need to be specified
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The replicas of the worker, need to be specified")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public AlluxioRuntimeSpec runAs(User runAs) {
    
    this.runAs = runAs;
    return this;
  }

   /**
   * Get runAs
   * @return runAs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public User getRunAs() {
    return runAs;
  }


  public void setRunAs(User runAs) {
    this.runAs = runAs;
  }


  public AlluxioRuntimeSpec tieredstore(TieredStore tieredstore) {
    
    this.tieredstore = tieredstore;
    return this;
  }

   /**
   * Get tieredstore
   * @return tieredstore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TieredStore getTieredstore() {
    return tieredstore;
  }


  public void setTieredstore(TieredStore tieredstore) {
    this.tieredstore = tieredstore;
  }


  public AlluxioRuntimeSpec volumes(List<V1Volume> volumes) {
    
    this.volumes = volumes;
    return this;
  }

  public AlluxioRuntimeSpec addVolumesItem(V1Volume volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<V1Volume>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

   /**
   * Volumes is the list of Kubernetes volumes that can be mounted by the alluxio runtime components and/or fuses.
   * @return volumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Volumes is the list of Kubernetes volumes that can be mounted by the alluxio runtime components and/or fuses.")

  public List<V1Volume> getVolumes() {
    return volumes;
  }


  public void setVolumes(List<V1Volume> volumes) {
    this.volumes = volumes;
  }


  public AlluxioRuntimeSpec worker(AlluxioCompTemplateSpec worker) {
    
    this.worker = worker;
    return this;
  }

   /**
   * Get worker
   * @return worker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlluxioCompTemplateSpec getWorker() {
    return worker;
  }


  public void setWorker(AlluxioCompTemplateSpec worker) {
    this.worker = worker;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlluxioRuntimeSpec alluxioRuntimeSpec = (AlluxioRuntimeSpec) o;
    return Objects.equals(this.alluxioVersion, alluxioRuntimeSpec.alluxioVersion) &&
        Objects.equals(this.apiGateway, alluxioRuntimeSpec.apiGateway) &&
        Objects.equals(this.data, alluxioRuntimeSpec.data) &&
        Objects.equals(this.disablePrometheus, alluxioRuntimeSpec.disablePrometheus) &&
        Objects.equals(this.fuse, alluxioRuntimeSpec.fuse) &&
        Objects.equals(this.hadoopConfig, alluxioRuntimeSpec.hadoopConfig) &&
        Objects.equals(this.initUsers, alluxioRuntimeSpec.initUsers) &&
        Objects.equals(this.jobMaster, alluxioRuntimeSpec.jobMaster) &&
        Objects.equals(this.jobWorker, alluxioRuntimeSpec.jobWorker) &&
        Objects.equals(this.jvmOptions, alluxioRuntimeSpec.jvmOptions) &&
        Objects.equals(this.management, alluxioRuntimeSpec.management) &&
        Objects.equals(this.master, alluxioRuntimeSpec.master) &&
        Objects.equals(this.podMetadata, alluxioRuntimeSpec.podMetadata) &&
        Objects.equals(this.properties, alluxioRuntimeSpec.properties) &&
        Objects.equals(this.replicas, alluxioRuntimeSpec.replicas) &&
        Objects.equals(this.runAs, alluxioRuntimeSpec.runAs) &&
        Objects.equals(this.tieredstore, alluxioRuntimeSpec.tieredstore) &&
        Objects.equals(this.volumes, alluxioRuntimeSpec.volumes) &&
        Objects.equals(this.worker, alluxioRuntimeSpec.worker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alluxioVersion, apiGateway, data, disablePrometheus, fuse, hadoopConfig, initUsers, jobMaster, jobWorker, jvmOptions, management, master, podMetadata, properties, replicas, runAs, tieredstore, volumes, worker);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlluxioRuntimeSpec {\n");
    sb.append("    alluxioVersion: ").append(toIndentedString(alluxioVersion)).append("\n");
    sb.append("    apiGateway: ").append(toIndentedString(apiGateway)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    disablePrometheus: ").append(toIndentedString(disablePrometheus)).append("\n");
    sb.append("    fuse: ").append(toIndentedString(fuse)).append("\n");
    sb.append("    hadoopConfig: ").append(toIndentedString(hadoopConfig)).append("\n");
    sb.append("    initUsers: ").append(toIndentedString(initUsers)).append("\n");
    sb.append("    jobMaster: ").append(toIndentedString(jobMaster)).append("\n");
    sb.append("    jobWorker: ").append(toIndentedString(jobWorker)).append("\n");
    sb.append("    jvmOptions: ").append(toIndentedString(jvmOptions)).append("\n");
    sb.append("    management: ").append(toIndentedString(management)).append("\n");
    sb.append("    master: ").append(toIndentedString(master)).append("\n");
    sb.append("    podMetadata: ").append(toIndentedString(podMetadata)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    runAs: ").append(toIndentedString(runAs)).append("\n");
    sb.append("    tieredstore: ").append(toIndentedString(tieredstore)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("    worker: ").append(toIndentedString(worker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

