/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.OperationRef;
import models.Processor;
import models.TargetDatasetWithMountPath;

/**
 * DataProcessSpec defines the desired state of DataProcess
 */
@ApiModel(description = "DataProcessSpec defines the desired state of DataProcess")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-30T14:39:14.140796+08:00[Asia/Shanghai]")
public class DataProcessSpec {
  public static final String SERIALIZED_NAME_DATASET = "dataset";
  @SerializedName(SERIALIZED_NAME_DATASET)
  private TargetDatasetWithMountPath dataset;

  public static final String SERIALIZED_NAME_PROCESSOR = "processor";
  @SerializedName(SERIALIZED_NAME_PROCESSOR)
  private Processor processor;

  public static final String SERIALIZED_NAME_RUN_AFTER = "runAfter";
  @SerializedName(SERIALIZED_NAME_RUN_AFTER)
  private OperationRef runAfter;

  public static final String SERIALIZED_NAME_TTL_SECONDS_AFTER_FINISHED = "ttlSecondsAfterFinished";
  @SerializedName(SERIALIZED_NAME_TTL_SECONDS_AFTER_FINISHED)
  private Integer ttlSecondsAfterFinished;


  public DataProcessSpec dataset(TargetDatasetWithMountPath dataset) {
    
    this.dataset = dataset;
    return this;
  }

   /**
   * Get dataset
   * @return dataset
  **/
  @ApiModelProperty(required = true, value = "")

  public TargetDatasetWithMountPath getDataset() {
    return dataset;
  }


  public void setDataset(TargetDatasetWithMountPath dataset) {
    this.dataset = dataset;
  }


  public DataProcessSpec processor(Processor processor) {
    
    this.processor = processor;
    return this;
  }

   /**
   * Get processor
   * @return processor
  **/
  @ApiModelProperty(required = true, value = "")

  public Processor getProcessor() {
    return processor;
  }


  public void setProcessor(Processor processor) {
    this.processor = processor;
  }


  public DataProcessSpec runAfter(OperationRef runAfter) {
    
    this.runAfter = runAfter;
    return this;
  }

   /**
   * Get runAfter
   * @return runAfter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OperationRef getRunAfter() {
    return runAfter;
  }


  public void setRunAfter(OperationRef runAfter) {
    this.runAfter = runAfter;
  }


  public DataProcessSpec ttlSecondsAfterFinished(Integer ttlSecondsAfterFinished) {
    
    this.ttlSecondsAfterFinished = ttlSecondsAfterFinished;
    return this;
  }

   /**
   * TTLSecondsAfterFinished is the time second to clean up data operations after finished or failed
   * @return ttlSecondsAfterFinished
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TTLSecondsAfterFinished is the time second to clean up data operations after finished or failed")

  public Integer getTtlSecondsAfterFinished() {
    return ttlSecondsAfterFinished;
  }


  public void setTtlSecondsAfterFinished(Integer ttlSecondsAfterFinished) {
    this.ttlSecondsAfterFinished = ttlSecondsAfterFinished;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataProcessSpec dataProcessSpec = (DataProcessSpec) o;
    return Objects.equals(this.dataset, dataProcessSpec.dataset) &&
        Objects.equals(this.processor, dataProcessSpec.processor) &&
        Objects.equals(this.runAfter, dataProcessSpec.runAfter) &&
        Objects.equals(this.ttlSecondsAfterFinished, dataProcessSpec.ttlSecondsAfterFinished);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataset, processor, runAfter, ttlSecondsAfterFinished);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataProcessSpec {\n");
    sb.append("    dataset: ").append(toIndentedString(dataset)).append("\n");
    sb.append("    processor: ").append(toIndentedString(processor)).append("\n");
    sb.append("    runAfter: ").append(toIndentedString(runAfter)).append("\n");
    sb.append("    ttlSecondsAfterFinished: ").append(toIndentedString(ttlSecondsAfterFinished)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

