/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DatasetToMigrate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-30T14:39:14.140796+08:00[Asia/Shanghai]")
public class DatasetToMigrate {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = "";

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace = "";

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;


  public DatasetToMigrate name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name of dataset
   * @return name
  **/
  @ApiModelProperty(required = true, value = "name of dataset")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DatasetToMigrate namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * namespace of dataset
   * @return namespace
  **/
  @ApiModelProperty(required = true, value = "namespace of dataset")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public DatasetToMigrate path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * path to migrate
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "path to migrate")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetToMigrate datasetToMigrate = (DatasetToMigrate) o;
    return Objects.equals(this.name, datasetToMigrate.name) &&
        Objects.equals(this.namespace, datasetToMigrate.namespace) &&
        Objects.equals(this.path, datasetToMigrate.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, namespace, path);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetToMigrate {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

