/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HCFS Endpoint info
 */
@ApiModel(description = "HCFS Endpoint info")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-30T11:55:35.636004+08:00[Asia/Shanghai]")
public class HCFSStatus {
  public static final String SERIALIZED_NAME_ENDPOINT = "endpoint";
  @SerializedName(SERIALIZED_NAME_ENDPOINT)
  private String endpoint;

  public static final String SERIALIZED_NAME_UNDERLAYER_FILE_SYSTEM_VERSION = "underlayerFileSystemVersion";
  @SerializedName(SERIALIZED_NAME_UNDERLAYER_FILE_SYSTEM_VERSION)
  private String underlayerFileSystemVersion;


  public HCFSStatus endpoint(String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Endpoint for accessing
   * @return endpoint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Endpoint for accessing")

  public String getEndpoint() {
    return endpoint;
  }


  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }


  public HCFSStatus underlayerFileSystemVersion(String underlayerFileSystemVersion) {
    
    this.underlayerFileSystemVersion = underlayerFileSystemVersion;
    return this;
  }

   /**
   * Underlayer HCFS Compatible Version
   * @return underlayerFileSystemVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Underlayer HCFS Compatible Version")

  public String getUnderlayerFileSystemVersion() {
    return underlayerFileSystemVersion;
  }


  public void setUnderlayerFileSystemVersion(String underlayerFileSystemVersion) {
    this.underlayerFileSystemVersion = underlayerFileSystemVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HCFSStatus hCFSStatus = (HCFSStatus) o;
    return Objects.equals(this.endpoint, hCFSStatus.endpoint) &&
        Objects.equals(this.underlayerFileSystemVersion, hCFSStatus.underlayerFileSystemVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpoint, underlayerFileSystemVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HCFSStatus {\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    underlayerFileSystemVersion: ").append(toIndentedString(underlayerFileSystemVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

