/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.V1PodSpec;

/**
 * JobProcessor
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-30T14:39:14.140796+08:00[Asia/Shanghai]")
public class JobProcessor {
  public static final String SERIALIZED_NAME_POD_SPEC = "podSpec";
  @SerializedName(SERIALIZED_NAME_POD_SPEC)
  private V1PodSpec podSpec = null;


  public JobProcessor podSpec(V1PodSpec podSpec) {
    
    this.podSpec = podSpec;
    return this;
  }

   /**
   * Get podSpec
   * @return podSpec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1PodSpec getPodSpec() {
    return podSpec;
  }


  public void setPodSpec(V1PodSpec podSpec) {
    this.podSpec = podSpec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobProcessor jobProcessor = (JobProcessor) o;
    return Objects.equals(this.podSpec, jobProcessor.podSpec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(podSpec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobProcessor {\n");
    sb.append("    podSpec: ").append(toIndentedString(podSpec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

