/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.K8sIoApimachineryPkgApiResourceQuantity;
import models.VolumeSource;

/**
 * Level describes configurations a tier needs. &lt;br&gt; Refer to &lt;a href&#x3D;\&quot;https://docs.alluxio.io/os/user/stable/en/core-services/Caching.html#configuring-tiered-storage\&quot;&gt;Configuring Tiered Storage&lt;/a&gt; for more info
 */
@ApiModel(description = "Level describes configurations a tier needs. <br> Refer to <a href=\"https://docs.alluxio.io/os/user/stable/en/core-services/Caching.html#configuring-tiered-storage\">Configuring Tiered Storage</a> for more info")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-30T11:55:35.636004+08:00[Asia/Shanghai]")
public class Level {
  public static final String SERIALIZED_NAME_HIGH = "high";
  @SerializedName(SERIALIZED_NAME_HIGH)
  private String high;

  public static final String SERIALIZED_NAME_LOW = "low";
  @SerializedName(SERIALIZED_NAME_LOW)
  private String low;

  public static final String SERIALIZED_NAME_MEDIUMTYPE = "mediumtype";
  @SerializedName(SERIALIZED_NAME_MEDIUMTYPE)
  private String mediumtype = "";

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_QUOTA = "quota";
  @SerializedName(SERIALIZED_NAME_QUOTA)
  private K8sIoApimachineryPkgApiResourceQuantity quota = null;

  public static final String SERIALIZED_NAME_QUOTA_LIST = "quotaList";
  @SerializedName(SERIALIZED_NAME_QUOTA_LIST)
  private String quotaList;

  public static final String SERIALIZED_NAME_VOLUME_SOURCE = "volumeSource";
  @SerializedName(SERIALIZED_NAME_VOLUME_SOURCE)
  private VolumeSource volumeSource;

  public static final String SERIALIZED_NAME_VOLUME_TYPE = "volumeType";
  @SerializedName(SERIALIZED_NAME_VOLUME_TYPE)
  private String volumeType = "";


  public Level high(String high) {
    
    this.high = high;
    return this;
  }

   /**
   * Ratio of high watermark of the tier (e.g. 0.9)
   * @return high
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ratio of high watermark of the tier (e.g. 0.9)")

  public String getHigh() {
    return high;
  }


  public void setHigh(String high) {
    this.high = high;
  }


  public Level low(String low) {
    
    this.low = low;
    return this;
  }

   /**
   * Ratio of low watermark of the tier (e.g. 0.7)
   * @return low
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ratio of low watermark of the tier (e.g. 0.7)")

  public String getLow() {
    return low;
  }


  public void setLow(String low) {
    this.low = low;
  }


  public Level mediumtype(String mediumtype) {
    
    this.mediumtype = mediumtype;
    return this;
  }

   /**
   * Medium Type of the tier. One of the three types: &#x60;MEM&#x60;, &#x60;SSD&#x60;, &#x60;HDD&#x60;
   * @return mediumtype
  **/
  @ApiModelProperty(required = true, value = "Medium Type of the tier. One of the three types: `MEM`, `SSD`, `HDD`")

  public String getMediumtype() {
    return mediumtype;
  }


  public void setMediumtype(String mediumtype) {
    this.mediumtype = mediumtype;
  }


  public Level path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * File paths to be used for the tier. Multiple paths are supported. Multiple paths should be separated with comma. For example: \&quot;/mnt/cache1,/mnt/cache2\&quot;.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "File paths to be used for the tier. Multiple paths are supported. Multiple paths should be separated with comma. For example: \"/mnt/cache1,/mnt/cache2\".")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public Level quota(K8sIoApimachineryPkgApiResourceQuantity quota) {
    
    this.quota = quota;
    return this;
  }

   /**
   * Get quota
   * @return quota
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public K8sIoApimachineryPkgApiResourceQuantity getQuota() {
    return quota;
  }


  public void setQuota(K8sIoApimachineryPkgApiResourceQuantity quota) {
    this.quota = quota;
  }


  public Level quotaList(String quotaList) {
    
    this.quotaList = quotaList;
    return this;
  }

   /**
   * QuotaList are quotas used to set quota on multiple paths. Quotas should be separated with comma. Quotas in this list will be set to paths with the same order in Path. For example, with Path defined with \&quot;/mnt/cache1,/mnt/cache2\&quot; and QuotaList set to \&quot;100Gi, 50Gi\&quot;, then we get 100GiB cache storage under \&quot;/mnt/cache1\&quot; and 50GiB under \&quot;/mnt/cache2\&quot;. Also note that num of quotas must be consistent with the num of paths defined in Path.
   * @return quotaList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "QuotaList are quotas used to set quota on multiple paths. Quotas should be separated with comma. Quotas in this list will be set to paths with the same order in Path. For example, with Path defined with \"/mnt/cache1,/mnt/cache2\" and QuotaList set to \"100Gi, 50Gi\", then we get 100GiB cache storage under \"/mnt/cache1\" and 50GiB under \"/mnt/cache2\". Also note that num of quotas must be consistent with the num of paths defined in Path.")

  public String getQuotaList() {
    return quotaList;
  }


  public void setQuotaList(String quotaList) {
    this.quotaList = quotaList;
  }


  public Level volumeSource(VolumeSource volumeSource) {
    
    this.volumeSource = volumeSource;
    return this;
  }

   /**
   * Get volumeSource
   * @return volumeSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VolumeSource getVolumeSource() {
    return volumeSource;
  }


  public void setVolumeSource(VolumeSource volumeSource) {
    this.volumeSource = volumeSource;
  }


  public Level volumeType(String volumeType) {
    
    this.volumeType = volumeType;
    return this;
  }

   /**
   * VolumeType is the volume type of the tier. Should be one of the three types: &#x60;hostPath&#x60;, &#x60;emptyDir&#x60; and &#x60;volumeTemplate&#x60;. If not set, defaults to hostPath.
   * @return volumeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VolumeType is the volume type of the tier. Should be one of the three types: `hostPath`, `emptyDir` and `volumeTemplate`. If not set, defaults to hostPath.")

  public String getVolumeType() {
    return volumeType;
  }


  public void setVolumeType(String volumeType) {
    this.volumeType = volumeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Level level = (Level) o;
    return Objects.equals(this.high, level.high) &&
        Objects.equals(this.low, level.low) &&
        Objects.equals(this.mediumtype, level.mediumtype) &&
        Objects.equals(this.path, level.path) &&
        Objects.equals(this.quota, level.quota) &&
        Objects.equals(this.quotaList, level.quotaList) &&
        Objects.equals(this.volumeSource, level.volumeSource) &&
        Objects.equals(this.volumeType, level.volumeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(high, low, mediumtype, path, quota, quotaList, volumeSource, volumeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Level {\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    mediumtype: ").append(toIndentedString(mediumtype)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    quotaList: ").append(toIndentedString(quotaList)).append("\n");
    sb.append("    volumeSource: ").append(toIndentedString(volumeSource)).append("\n");
    sb.append("    volumeType: ").append(toIndentedString(volumeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

