/*
 * fluid
 * client for fluid
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import models.MasterSpec;
import models.TieredStore;
import models.V1Volume;
import models.VineyardCompTemplateSpec;
import models.VineyardSockSpec;

/**
 * VineyardRuntimeSpec defines the desired state of VineyardRuntime
 */
@ApiModel(description = "VineyardRuntimeSpec defines the desired state of VineyardRuntime")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-15T22:35:53.526622+08:00[Asia/Shanghai]")
public class VineyardRuntimeSpec {
  public static final String SERIALIZED_NAME_DISABLE_PROMETHEUS = "disablePrometheus";
  @SerializedName(SERIALIZED_NAME_DISABLE_PROMETHEUS)
  private Boolean disablePrometheus;

  public static final String SERIALIZED_NAME_FUSE = "fuse";
  @SerializedName(SERIALIZED_NAME_FUSE)
  private VineyardSockSpec fuse;

  public static final String SERIALIZED_NAME_MASTER = "master";
  @SerializedName(SERIALIZED_NAME_MASTER)
  private MasterSpec master;

  public static final String SERIALIZED_NAME_TIEREDSTORE = "tieredstore";
  @SerializedName(SERIALIZED_NAME_TIEREDSTORE)
  private TieredStore tieredstore;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  private List<V1Volume> volumes = null;

  public static final String SERIALIZED_NAME_WORKER = "worker";
  @SerializedName(SERIALIZED_NAME_WORKER)
  private VineyardCompTemplateSpec worker;


  public VineyardRuntimeSpec disablePrometheus(Boolean disablePrometheus) {
    
    this.disablePrometheus = disablePrometheus;
    return this;
  }

   /**
   * Disable monitoring metrics for Vineyard Runtime Default is false
   * @return disablePrometheus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable monitoring metrics for Vineyard Runtime Default is false")

  public Boolean getDisablePrometheus() {
    return disablePrometheus;
  }


  public void setDisablePrometheus(Boolean disablePrometheus) {
    this.disablePrometheus = disablePrometheus;
  }


  public VineyardRuntimeSpec fuse(VineyardSockSpec fuse) {
    
    this.fuse = fuse;
    return this;
  }

   /**
   * Get fuse
   * @return fuse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VineyardSockSpec getFuse() {
    return fuse;
  }


  public void setFuse(VineyardSockSpec fuse) {
    this.fuse = fuse;
  }


  public VineyardRuntimeSpec master(MasterSpec master) {
    
    this.master = master;
    return this;
  }

   /**
   * Get master
   * @return master
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MasterSpec getMaster() {
    return master;
  }


  public void setMaster(MasterSpec master) {
    this.master = master;
  }


  public VineyardRuntimeSpec tieredstore(TieredStore tieredstore) {
    
    this.tieredstore = tieredstore;
    return this;
  }

   /**
   * Get tieredstore
   * @return tieredstore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TieredStore getTieredstore() {
    return tieredstore;
  }


  public void setTieredstore(TieredStore tieredstore) {
    this.tieredstore = tieredstore;
  }


  public VineyardRuntimeSpec volumes(List<V1Volume> volumes) {
    
    this.volumes = volumes;
    return this;
  }

  public VineyardRuntimeSpec addVolumesItem(V1Volume volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<V1Volume>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

   /**
   * Volumes is the list of Kubernetes volumes that can be mounted by the vineyard components (Master and Worker). Default is null.
   * @return volumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Volumes is the list of Kubernetes volumes that can be mounted by the vineyard components (Master and Worker). Default is null.")

  public List<V1Volume> getVolumes() {
    return volumes;
  }


  public void setVolumes(List<V1Volume> volumes) {
    this.volumes = volumes;
  }


  public VineyardRuntimeSpec worker(VineyardCompTemplateSpec worker) {
    
    this.worker = worker;
    return this;
  }

   /**
   * Get worker
   * @return worker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VineyardCompTemplateSpec getWorker() {
    return worker;
  }


  public void setWorker(VineyardCompTemplateSpec worker) {
    this.worker = worker;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VineyardRuntimeSpec vineyardRuntimeSpec = (VineyardRuntimeSpec) o;
    return Objects.equals(this.disablePrometheus, vineyardRuntimeSpec.disablePrometheus) &&
        Objects.equals(this.fuse, vineyardRuntimeSpec.fuse) &&
        Objects.equals(this.master, vineyardRuntimeSpec.master) &&
        Objects.equals(this.tieredstore, vineyardRuntimeSpec.tieredstore) &&
        Objects.equals(this.volumes, vineyardRuntimeSpec.volumes) &&
        Objects.equals(this.worker, vineyardRuntimeSpec.worker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disablePrometheus, fuse, master, tieredstore, volumes, worker);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VineyardRuntimeSpec {\n");
    sb.append("    disablePrometheus: ").append(toIndentedString(disablePrometheus)).append("\n");
    sb.append("    fuse: ").append(toIndentedString(fuse)).append("\n");
    sb.append("    master: ").append(toIndentedString(master)).append("\n");
    sb.append("    tieredstore: ").append(toIndentedString(tieredstore)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("    worker: ").append(toIndentedString(worker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

